version: '3'

services:
  api:
    container_name: api
    tty: true
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./app:/app
    depends_on:
      - db
    
  db:
    container_name: db
    build: 
      context: .
      dockerfile: docker/db/Dockerfile
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-store:/var/lib/postgresql/data
    restart: always

volumes:
  db-store: