version: '3'

services:
  api:
    container_name: favorite-character-api
    tty: true
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    ports:
      - 8081:8080
    volumes:
      - ./app:/app
    depends_on:
      - db
    env_file: .env
    
  db:
    container_name: favorite-character-db
    build: 
      context: .
      dockerfile: docker/db/Dockerfile
    ports:
      - 6000:6000
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-store:/var/lib/postgresql/data
    restart: always

volumes:
  db-store: